# Generated by Django 5.1.7 on 2025-03-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('call_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('membership_expires', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
