# Generated by Django 5.1.7 on 2025-03-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_registered',
        ),
        migrations.AddField(
            model_name='member',
            name='dues_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='call_sign',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
