name: Cleanup Containers on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: branch-builds
    permissions:
      packages: write  # Required for deleting GHCR images

    steps:
      - name: Convert owner name to lowercase
        id: lowercase
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Get merged branch name
        id: branch_name
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHRC_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GHRC_TOKEN }}" | gh auth login --with-token

      - name: Get list of image versions for merged branch
        run: |
          gh api /user/packages/container/k0iro-members/versions --jq '.[] | select(.metadata.container.tags[] | contains("${{ env.BRANCH_NAME }}")) | .id' > version_ids.txt

      - name: Delete all images & tags for the branch
        run: |
          for ID in $(cat version_ids.txt); do
            gh api --method DELETE /user/packages/container/k0iro-members/versions/$ID
          done
