name: k0iro members build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [meshmapdmz]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: /var/www/k0iro-members

    #- name: Set Working Directory
    #  run: cd /var/www/k0iro-members && pwd

    - name: Stop Django service
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl stop k0iromembers.service

    - name: Pull latest changes
      working-directory: /var/www/k0iro-members
      run: git pull

    - name: Run Django migrations
      working-directory: /var/www/k0iro-members
      run: |
        python manage.py makemigrations
        python manage.py migrate


    - name: Start Django service
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl start k0iromembers.service
