name: k0iro members build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [meshmapdmz]

    steps:
    - name: Stop Django service
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl stop k0iromembers.service

    - name: Pull latest changes
      working-directory: /var/www/k0iro-members
      run: git pull

    - name: Install Any Requirements
      working-directory: /var/www/k0iro-members
      run: pip install -r requirements.txt

    - name: Run Django migrations
      working-directory: /var/www/k0iro-members
      run: |
        python manage.py makemigrations
        python manage.py migrate


    - name: Start Django service
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl start k0iromembers.service
