name: k0iro members build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Convert owner name to lowercase
        id: lowercase
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHRC_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.OWNER_LC }}/k0iro-members:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ env.OWNER_LC }}/k0iro-members:latest
